version: '3.8'

services:
  # MongoDB - Database chính
  mongodb:
    image: mongo:latest
    container_name: bot-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - bot-network

  # Redis - Dùng cho Task Queue (Arq) và Caching
  redis:
    image: redis/redis-stack:latest
    container_name: bot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  qdrant_data:
