version: '3.8'

services:
  # Ứng dụng Bot Server chính
  bot-server:
    image: ghcr.io/${GITHUB_REPOSITORY_LOWER}-bot-server:release # Thay bằng đường dẫn thực tế sau khi push
    container_name: bot-server-app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./logs:/app/logs
      - ./static/uploads:/app/static/uploads
    networks:
      - bot-network

  # MongoDB - Database chính
  mongodb:
    image: mongo:4.4.18
    container_name: bot-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - bot-network

  # Redis - Dùng cho Task Queue (Arq) và Caching
  redis:
    image: redis/redis-stack:latest
    container_name: bot-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  qdrant_data:
